### PR TITLE
Russian updates

### PR DESCRIPTION
**Pull request by contributorpw**

### CODE REVIEW

**Comment by jthegedus** [comment]
You're a legend! 🎉

**Comment by contributorpw** [comment]
@jthegedus , this repo is awesome!

I fell in love :heart: with the simplicity and usefulness of this content.

**Comment by jthegedus** [comment]
I removed the ref style links. If you get a chance, could you see if there are any issues in this diff https://github.com/jthegedus/awesome-firebase/commit/699a06076e3a34dc6747593c24dc7316b20cfe38 ?

**Comment by contributorpw** [comment]
- [ ] Check links
- [ ] Recheck the main file

**Pull request merged**
